name: Build

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        java_vendor: [ temurin, zulu, liberica, microsoft, corretto ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.java_vendor }}
          java-version: 17
      - name: Build on ${{ matrix.os }}
        run: ./gradlew clean build
